// warning: this file was auto generated!
var OpCodes = {
  "Nop": {
    "name": "nop",
    "size": 1,
    "value": 0,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Break": {
    "name": "break",
    "size": 1,
    "value": 1,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Break,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Ldarg_0": {
    "name": "ldarg.0",
    "size": 1,
    "value": 2,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldarg_1": {
    "name": "ldarg.1",
    "size": 1,
    "value": 3,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldarg_2": {
    "name": "ldarg.2",
    "size": 1,
    "value": 4,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldarg_3": {
    "name": "ldarg.3",
    "size": 1,
    "value": 5,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloc_0": {
    "name": "ldloc.0",
    "size": 1,
    "value": 6,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloc_1": {
    "name": "ldloc.1",
    "size": 1,
    "value": 7,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloc_2": {
    "name": "ldloc.2",
    "size": 1,
    "value": 8,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloc_3": {
    "name": "ldloc.3",
    "size": 1,
    "value": 9,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Stloc_0": {
    "name": "stloc.0",
    "size": 1,
    "value": 10,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Stloc_1": {
    "name": "stloc.1",
    "size": 1,
    "value": 11,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Stloc_2": {
    "name": "stloc.2",
    "size": 1,
    "value": 12,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Stloc_3": {
    "name": "stloc.3",
    "size": 1,
    "value": 13,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Ldarg_S": {
    "name": "ldarg.s",
    "size": 1,
    "value": 14,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldarga_S": {
    "name": "ldarga.s",
    "size": 1,
    "value": 15,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Starg_S": {
    "name": "starg.s",
    "size": 1,
    "value": 16,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Ldloc_S": {
    "name": "ldloc.s",
    "size": 1,
    "value": 17,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloca_S": {
    "name": "ldloca.s",
    "size": 1,
    "value": 18,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Stloc_S": {
    "name": "stloc.s",
    "size": 1,
    "value": 19,
    "operand": OperandType.ShortInlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Ldnull": {
    "name": "ldnull",
    "size": 1,
    "value": 20,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushref
  },
  "Ldc_I4_M1": {
    "name": "ldc.i4.m1",
    "size": 1,
    "value": 21,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_0": {
    "name": "ldc.i4.0",
    "size": 1,
    "value": 22,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_1": {
    "name": "ldc.i4.1",
    "size": 1,
    "value": 23,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_2": {
    "name": "ldc.i4.2",
    "size": 1,
    "value": 24,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_3": {
    "name": "ldc.i4.3",
    "size": 1,
    "value": 25,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_4": {
    "name": "ldc.i4.4",
    "size": 1,
    "value": 26,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_5": {
    "name": "ldc.i4.5",
    "size": 1,
    "value": 27,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_6": {
    "name": "ldc.i4.6",
    "size": 1,
    "value": 28,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_7": {
    "name": "ldc.i4.7",
    "size": 1,
    "value": 29,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_8": {
    "name": "ldc.i4.8",
    "size": 1,
    "value": 30,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4_S": {
    "name": "ldc.i4.s",
    "size": 1,
    "value": 31,
    "operand": OperandType.ShortInlineI,
    "flow": FlowControl.Next,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I4": {
    "name": "ldc.i4",
    "size": 1,
    "value": 32,
    "operand": OperandType.InlineI,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldc_I8": {
    "name": "ldc.i8",
    "size": 1,
    "value": 33,
    "operand": OperandType.InlineI8,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi8
  },
  "Ldc_R4": {
    "name": "ldc.r4",
    "size": 1,
    "value": 34,
    "operand": OperandType.ShortInlineR,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushr4
  },
  "Ldc_R8": {
    "name": "ldc.r8",
    "size": 1,
    "value": 35,
    "operand": OperandType.InlineR,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushr8
  },
  "Dup": {
    "name": "dup",
    "size": 1,
    "value": 37,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push1_push1
  },
  "Pop": {
    "name": "pop",
    "size": 1,
    "value": 38,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Jmp": {
    "name": "jmp",
    "size": 1,
    "value": 39,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Call,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Call": {
    "name": "call",
    "size": 1,
    "value": 40,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Call,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Varpop,
    "push": StackBehaviour.Varpush
  },
  "Calli": {
    "name": "calli",
    "size": 1,
    "value": 41,
    "operand": OperandType.InlineSig,
    "flow": FlowControl.Call,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Varpop,
    "push": StackBehaviour.Varpush
  },
  "Ret": {
    "name": "ret",
    "size": 1,
    "value": 42,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Return,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Varpop,
    "push": StackBehaviour.Push0
  },
  "Br_S": {
    "name": "br.s",
    "size": 1,
    "value": 43,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Brfalse_S": {
    "name": "brfalse.s",
    "size": 1,
    "value": 44,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Brtrue_S": {
    "name": "brtrue.s",
    "size": 1,
    "value": 45,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Beq_S": {
    "name": "beq.s",
    "size": 1,
    "value": 46,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bge_S": {
    "name": "bge.s",
    "size": 1,
    "value": 47,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bgt_S": {
    "name": "bgt.s",
    "size": 1,
    "value": 48,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Ble_S": {
    "name": "ble.s",
    "size": 1,
    "value": 49,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Blt_S": {
    "name": "blt.s",
    "size": 1,
    "value": 50,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bne_Un_S": {
    "name": "bne.un.s",
    "size": 1,
    "value": 51,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bge_Un_S": {
    "name": "bge.un.s",
    "size": 1,
    "value": 52,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bgt_Un_S": {
    "name": "bgt.un.s",
    "size": 1,
    "value": 53,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Ble_Un_S": {
    "name": "ble.un.s",
    "size": 1,
    "value": 54,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Blt_Un_S": {
    "name": "blt.un.s",
    "size": 1,
    "value": 55,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Br": {
    "name": "br",
    "size": 1,
    "value": 56,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Brfalse": {
    "name": "brfalse",
    "size": 1,
    "value": 57,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Brtrue": {
    "name": "brtrue",
    "size": 1,
    "value": 58,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Beq": {
    "name": "beq",
    "size": 1,
    "value": 59,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bge": {
    "name": "bge",
    "size": 1,
    "value": 60,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bgt": {
    "name": "bgt",
    "size": 1,
    "value": 61,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Ble": {
    "name": "ble",
    "size": 1,
    "value": 62,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Blt": {
    "name": "blt",
    "size": 1,
    "value": 63,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bne_Un": {
    "name": "bne.un",
    "size": 1,
    "value": 64,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bge_Un": {
    "name": "bge.un",
    "size": 1,
    "value": 65,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Bgt_Un": {
    "name": "bgt.un",
    "size": 1,
    "value": 66,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Ble_Un": {
    "name": "ble.un",
    "size": 1,
    "value": 67,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Blt_Un": {
    "name": "blt.un",
    "size": 1,
    "value": 68,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Macro,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push0
  },
  "Switch": {
    "name": "switch",
    "size": 1,
    "value": 69,
    "operand": OperandType.InlineSwitch,
    "flow": FlowControl.Cond_Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Ldind_I1": {
    "name": "ldind.i1",
    "size": 1,
    "value": 70,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_U1": {
    "name": "ldind.u1",
    "size": 1,
    "value": 71,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_I2": {
    "name": "ldind.i2",
    "size": 1,
    "value": 72,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_U2": {
    "name": "ldind.u2",
    "size": 1,
    "value": 73,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_I4": {
    "name": "ldind.i4",
    "size": 1,
    "value": 74,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_U4": {
    "name": "ldind.u4",
    "size": 1,
    "value": 75,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_I8": {
    "name": "ldind.i8",
    "size": 1,
    "value": 76,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi8
  },
  "Ldind_I": {
    "name": "ldind.i",
    "size": 1,
    "value": 77,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Ldind_R4": {
    "name": "ldind.r4",
    "size": 1,
    "value": 78,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushr4
  },
  "Ldind_R8": {
    "name": "ldind.r8",
    "size": 1,
    "value": 79,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushr8
  },
  "Ldind_Ref": {
    "name": "ldind.ref",
    "size": 1,
    "value": 80,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushref
  },
  "Stind_Ref": {
    "name": "stind.ref",
    "size": 1,
    "value": 81,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stind_I1": {
    "name": "stind.i1",
    "size": 1,
    "value": 82,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stind_I2": {
    "name": "stind.i2",
    "size": 1,
    "value": 83,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stind_I4": {
    "name": "stind.i4",
    "size": 1,
    "value": 84,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stind_I8": {
    "name": "stind.i8",
    "size": 1,
    "value": 85,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi8,
    "push": StackBehaviour.Push0
  },
  "Stind_R4": {
    "name": "stind.r4",
    "size": 1,
    "value": 86,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popr4,
    "push": StackBehaviour.Push0
  },
  "Stind_R8": {
    "name": "stind.r8",
    "size": 1,
    "value": 87,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popr8,
    "push": StackBehaviour.Push0
  },
  "Add": {
    "name": "add",
    "size": 1,
    "value": 88,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Sub": {
    "name": "sub",
    "size": 1,
    "value": 89,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Mul": {
    "name": "mul",
    "size": 1,
    "value": 90,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Div": {
    "name": "div",
    "size": 1,
    "value": 91,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Div_Un": {
    "name": "div.un",
    "size": 1,
    "value": 92,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Rem": {
    "name": "rem",
    "size": 1,
    "value": 93,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Rem_Un": {
    "name": "rem.un",
    "size": 1,
    "value": 94,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "And": {
    "name": "and",
    "size": 1,
    "value": 95,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Or": {
    "name": "or",
    "size": 1,
    "value": 96,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Xor": {
    "name": "xor",
    "size": 1,
    "value": 97,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Shl": {
    "name": "shl",
    "size": 1,
    "value": 98,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Shr": {
    "name": "shr",
    "size": 1,
    "value": 99,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Shr_Un": {
    "name": "shr.un",
    "size": 1,
    "value": 100,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Neg": {
    "name": "neg",
    "size": 1,
    "value": 101,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push1
  },
  "Not": {
    "name": "not",
    "size": 1,
    "value": 102,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push1
  },
  "Conv_I1": {
    "name": "conv.i1",
    "size": 1,
    "value": 103,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_I2": {
    "name": "conv.i2",
    "size": 1,
    "value": 104,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_I4": {
    "name": "conv.i4",
    "size": 1,
    "value": 105,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_I8": {
    "name": "conv.i8",
    "size": 1,
    "value": 106,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Conv_R4": {
    "name": "conv.r4",
    "size": 1,
    "value": 107,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushr4
  },
  "Conv_R8": {
    "name": "conv.r8",
    "size": 1,
    "value": 108,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushr8
  },
  "Conv_U4": {
    "name": "conv.u4",
    "size": 1,
    "value": 109,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_U8": {
    "name": "conv.u8",
    "size": 1,
    "value": 110,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Callvirt": {
    "name": "callvirt",
    "size": 1,
    "value": 111,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Call,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Varpop,
    "push": StackBehaviour.Varpush
  },
  "Cpobj": {
    "name": "cpobj",
    "size": 1,
    "value": 112,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Ldobj": {
    "name": "ldobj",
    "size": 1,
    "value": 113,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push1
  },
  "Ldstr": {
    "name": "ldstr",
    "size": 1,
    "value": 114,
    "operand": OperandType.InlineString,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushref
  },
  "Newobj": {
    "name": "newobj",
    "size": 1,
    "value": 115,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Call,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Varpop,
    "push": StackBehaviour.Pushref
  },
  "Castclass": {
    "name": "castclass",
    "size": 1,
    "value": 116,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushref
  },
  "Isinst": {
    "name": "isinst",
    "size": 1,
    "value": 117,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushi
  },
  "Conv_R_Un": {
    "name": "conv.r.un",
    "size": 1,
    "value": 118,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushr8
  },
  "Unbox": {
    "name": "unbox",
    "size": 1,
    "value": 121,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushi
  },
  "Throw": {
    "name": "throw",
    "size": 1,
    "value": 122,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Throw,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Push0
  },
  "Ldfld": {
    "name": "ldfld",
    "size": 1,
    "value": 123,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Push1
  },
  "Ldflda": {
    "name": "ldflda",
    "size": 1,
    "value": 124,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushi
  },
  "Stfld": {
    "name": "stfld",
    "size": 1,
    "value": 125,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_pop1,
    "push": StackBehaviour.Push0
  },
  "Ldsfld": {
    "name": "ldsfld",
    "size": 1,
    "value": 126,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldsflda": {
    "name": "ldsflda",
    "size": 1,
    "value": 127,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Stsfld": {
    "name": "stsfld",
    "size": 1,
    "value": 128,
    "operand": OperandType.InlineField,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Stobj": {
    "name": "stobj",
    "size": 1,
    "value": 129,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_pop1,
    "push": StackBehaviour.Push0
  },
  "Conv_Ovf_I1_Un": {
    "name": "conv.ovf.i1.un",
    "size": 1,
    "value": 130,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I2_Un": {
    "name": "conv.ovf.i2.un",
    "size": 1,
    "value": 131,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I4_Un": {
    "name": "conv.ovf.i4.un",
    "size": 1,
    "value": 132,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I8_Un": {
    "name": "conv.ovf.i8.un",
    "size": 1,
    "value": 133,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Conv_Ovf_U1_Un": {
    "name": "conv.ovf.u1.un",
    "size": 1,
    "value": 134,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U2_Un": {
    "name": "conv.ovf.u2.un",
    "size": 1,
    "value": 135,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U4_Un": {
    "name": "conv.ovf.u4.un",
    "size": 1,
    "value": 136,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U8_Un": {
    "name": "conv.ovf.u8.un",
    "size": 1,
    "value": 137,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Conv_Ovf_I_Un": {
    "name": "conv.ovf.i.un",
    "size": 1,
    "value": 138,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U_Un": {
    "name": "conv.ovf.u.un",
    "size": 1,
    "value": 139,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Box": {
    "name": "box",
    "size": 1,
    "value": 140,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushref
  },
  "Newarr": {
    "name": "newarr",
    "size": 1,
    "value": 141,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushref
  },
  "Ldlen": {
    "name": "ldlen",
    "size": 1,
    "value": 142,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushi
  },
  "Ldelema": {
    "name": "ldelema",
    "size": 1,
    "value": 143,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_I1": {
    "name": "ldelem.i1",
    "size": 1,
    "value": 144,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_U1": {
    "name": "ldelem.u1",
    "size": 1,
    "value": 145,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_I2": {
    "name": "ldelem.i2",
    "size": 1,
    "value": 146,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_U2": {
    "name": "ldelem.u2",
    "size": 1,
    "value": 147,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_I4": {
    "name": "ldelem.i4",
    "size": 1,
    "value": 148,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_U4": {
    "name": "ldelem.u4",
    "size": 1,
    "value": 149,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_I8": {
    "name": "ldelem.i8",
    "size": 1,
    "value": 150,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi8
  },
  "Ldelem_I": {
    "name": "ldelem.i",
    "size": 1,
    "value": 151,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushi
  },
  "Ldelem_R4": {
    "name": "ldelem.r4",
    "size": 1,
    "value": 152,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushr4
  },
  "Ldelem_R8": {
    "name": "ldelem.r8",
    "size": 1,
    "value": 153,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushr8
  },
  "Ldelem_Ref": {
    "name": "ldelem.ref",
    "size": 1,
    "value": 154,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Pushref
  },
  "Stelem_I": {
    "name": "stelem.i",
    "size": 1,
    "value": 155,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stelem_I1": {
    "name": "stelem.i1",
    "size": 1,
    "value": 156,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stelem_I2": {
    "name": "stelem.i2",
    "size": 1,
    "value": 157,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stelem_I4": {
    "name": "stelem.i4",
    "size": 1,
    "value": 158,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Stelem_I8": {
    "name": "stelem.i8",
    "size": 1,
    "value": 159,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popi8,
    "push": StackBehaviour.Push0
  },
  "Stelem_R4": {
    "name": "stelem.r4",
    "size": 1,
    "value": 160,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popr4,
    "push": StackBehaviour.Push0
  },
  "Stelem_R8": {
    "name": "stelem.r8",
    "size": 1,
    "value": 161,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popr8,
    "push": StackBehaviour.Push0
  },
  "Stelem_Ref": {
    "name": "stelem.ref",
    "size": 1,
    "value": 162,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_popref,
    "push": StackBehaviour.Push0
  },
  "Ldelem": {
    "name": "ldelem",
    "size": 1,
    "value": 163,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi,
    "push": StackBehaviour.Push1
  },
  "Stelem": {
    "name": "stelem",
    "size": 1,
    "value": 164,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref_popi_pop1,
    "push": StackBehaviour.Push0
  },
  "Unbox_Any": {
    "name": "unbox.any",
    "size": 1,
    "value": 165,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Push1
  },
  "Conv_Ovf_I1": {
    "name": "conv.ovf.i1",
    "size": 1,
    "value": 179,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U1": {
    "name": "conv.ovf.u1",
    "size": 1,
    "value": 180,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I2": {
    "name": "conv.ovf.i2",
    "size": 1,
    "value": 181,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U2": {
    "name": "conv.ovf.u2",
    "size": 1,
    "value": 182,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I4": {
    "name": "conv.ovf.i4",
    "size": 1,
    "value": 183,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U4": {
    "name": "conv.ovf.u4",
    "size": 1,
    "value": 184,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I8": {
    "name": "conv.ovf.i8",
    "size": 1,
    "value": 185,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Conv_Ovf_U8": {
    "name": "conv.ovf.u8",
    "size": 1,
    "value": 186,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi8
  },
  "Refanyval": {
    "name": "refanyval",
    "size": 1,
    "value": 194,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Ckfinite": {
    "name": "ckfinite",
    "size": 1,
    "value": 195,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushr8
  },
  "Mkrefany": {
    "name": "mkrefany",
    "size": 1,
    "value": 198,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push1
  },
  "Ldtoken": {
    "name": "ldtoken",
    "size": 1,
    "value": 208,
    "operand": OperandType.InlineTok,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Conv_U2": {
    "name": "conv.u2",
    "size": 1,
    "value": 209,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_U1": {
    "name": "conv.u1",
    "size": 1,
    "value": 210,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_I": {
    "name": "conv.i",
    "size": 1,
    "value": 211,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_I": {
    "name": "conv.ovf.i",
    "size": 1,
    "value": 212,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Conv_Ovf_U": {
    "name": "conv.ovf.u",
    "size": 1,
    "value": 213,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Add_Ovf": {
    "name": "add.ovf",
    "size": 1,
    "value": 214,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Add_Ovf_Un": {
    "name": "add.ovf.un",
    "size": 1,
    "value": 215,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Mul_Ovf": {
    "name": "mul.ovf",
    "size": 1,
    "value": 216,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Mul_Ovf_Un": {
    "name": "mul.ovf.un",
    "size": 1,
    "value": 217,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Sub_Ovf": {
    "name": "sub.ovf",
    "size": 1,
    "value": 218,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Sub_Ovf_Un": {
    "name": "sub.ovf.un",
    "size": 1,
    "value": 219,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Push1
  },
  "Endfinally": {
    "name": "endfinally",
    "size": 1,
    "value": 220,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Return,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Leave": {
    "name": "leave",
    "size": 1,
    "value": 221,
    "operand": OperandType.InlineBrTarget,
    "flow": FlowControl.Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Leave_S": {
    "name": "leave.s",
    "size": 1,
    "value": 222,
    "operand": OperandType.ShortInlineBrTarget,
    "flow": FlowControl.Branch,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Stind_I": {
    "name": "stind.i",
    "size": 1,
    "value": 223,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi,
    "push": StackBehaviour.Push0
  },
  "Conv_U": {
    "name": "conv.u",
    "size": 1,
    "value": 224,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Prefix7": {
    "name": "prefix7",
    "size": 1,
    "value": 248,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix6": {
    "name": "prefix6",
    "size": 1,
    "value": 249,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix5": {
    "name": "prefix5",
    "size": 1,
    "value": 250,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix4": {
    "name": "prefix4",
    "size": 1,
    "value": 251,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix3": {
    "name": "prefix3",
    "size": 1,
    "value": 252,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix2": {
    "name": "prefix2",
    "size": 1,
    "value": 253,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefix1": {
    "name": "prefix1",
    "size": 1,
    "value": 254,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Prefixref": {
    "name": "prefixref",
    "size": 1,
    "value": 255,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Nternal,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Arglist": {
    "name": "arglist",
    "size": 2,
    "value": -512,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ceq": {
    "name": "ceq",
    "size": 2,
    "value": -511,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Pushi
  },
  "Cgt": {
    "name": "cgt",
    "size": 2,
    "value": -510,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Pushi
  },
  "Cgt_Un": {
    "name": "cgt.un",
    "size": 2,
    "value": -509,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Pushi
  },
  "Clt": {
    "name": "clt",
    "size": 2,
    "value": -508,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Pushi
  },
  "Clt_Un": {
    "name": "clt.un",
    "size": 2,
    "value": -507,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1_pop1,
    "push": StackBehaviour.Pushi
  },
  "Ldftn": {
    "name": "ldftn",
    "size": 2,
    "value": -506,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Ldvirtftn": {
    "name": "ldvirtftn",
    "size": 2,
    "value": -505,
    "operand": OperandType.InlineMethod,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popref,
    "push": StackBehaviour.Pushi
  },
  "Ldarg": {
    "name": "ldarg",
    "size": 2,
    "value": -503,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldarga": {
    "name": "ldarga",
    "size": 2,
    "value": -502,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Starg": {
    "name": "starg",
    "size": 2,
    "value": -501,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Ldloc": {
    "name": "ldloc",
    "size": 2,
    "value": -500,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push1
  },
  "Ldloca": {
    "name": "ldloca",
    "size": 2,
    "value": -499,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Stloc": {
    "name": "stloc",
    "size": 2,
    "value": -498,
    "operand": OperandType.InlineVar,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Push0
  },
  "Localloc": {
    "name": "localloc",
    "size": 2,
    "value": -497,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Pushi
  },
  "Endfilter": {
    "name": "endfilter",
    "size": 2,
    "value": -495,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Return,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Unaligned": {
    "name": "unaligned.",
    "size": 2,
    "value": -494,
    "operand": OperandType.ShortInlineI,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Prefix,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Volatile": {
    "name": "volatile.",
    "size": 2,
    "value": -493,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Prefix,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Tailcall": {
    "name": "tail.",
    "size": 2,
    "value": -492,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Prefix,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Initobj": {
    "name": "initobj",
    "size": 2,
    "value": -491,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Popi,
    "push": StackBehaviour.Push0
  },
  "Constrained": {
    "name": "constrained.",
    "size": 2,
    "value": -490,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Prefix,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Cpblk": {
    "name": "cpblk",
    "size": 2,
    "value": -489,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Initblk": {
    "name": "initblk",
    "size": 2,
    "value": -488,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Popi_popi_popi,
    "push": StackBehaviour.Push0
  },
  "Rethrow": {
    "name": "rethrow",
    "size": 2,
    "value": -486,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Throw,
    "type": OpCodeType.Objmodel,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  },
  "Sizeof": {
    "name": "sizeof",
    "size": 2,
    "value": -484,
    "operand": OperandType.InlineType,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Pushi
  },
  "Refanytype": {
    "name": "refanytype",
    "size": 2,
    "value": -483,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Next,
    "type": OpCodeType.Primitive,
    "pop": StackBehaviour.Pop1,
    "push": StackBehaviour.Pushi
  },
  "Readonly": {
    "name": "readonly.",
    "size": 2,
    "value": -482,
    "operand": OperandType.InlineNone,
    "flow": FlowControl.Meta,
    "type": OpCodeType.Prefix,
    "pop": StackBehaviour.Pop0,
    "push": StackBehaviour.Push0
  }
};
var ShortOpCodes = [
  OpCodes.Nop,
  OpCodes.Break,
  OpCodes.Ldarg_0,
  OpCodes.Ldarg_1,
  OpCodes.Ldarg_2,
  OpCodes.Ldarg_3,
  OpCodes.Ldloc_0,
  OpCodes.Ldloc_1,
  OpCodes.Ldloc_2,
  OpCodes.Ldloc_3,
  OpCodes.Stloc_0,
  OpCodes.Stloc_1,
  OpCodes.Stloc_2,
  OpCodes.Stloc_3,
  OpCodes.Ldarg_S,
  OpCodes.Ldarga_S,
  OpCodes.Starg_S,
  OpCodes.Ldloc_S,
  OpCodes.Ldloca_S,
  OpCodes.Stloc_S,
  OpCodes.Ldnull,
  OpCodes.Ldc_I4_M1,
  OpCodes.Ldc_I4_0,
  OpCodes.Ldc_I4_1,
  OpCodes.Ldc_I4_2,
  OpCodes.Ldc_I4_3,
  OpCodes.Ldc_I4_4,
  OpCodes.Ldc_I4_5,
  OpCodes.Ldc_I4_6,
  OpCodes.Ldc_I4_7,
  OpCodes.Ldc_I4_8,
  OpCodes.Ldc_I4_S,
  OpCodes.Ldc_I4,
  OpCodes.Ldc_I8,
  OpCodes.Ldc_R4,
  OpCodes.Ldc_R8,
  null,
  OpCodes.Dup,
  OpCodes.Pop,
  OpCodes.Jmp,
  OpCodes.Call,
  OpCodes.Calli,
  OpCodes.Ret,
  OpCodes.Br_S,
  OpCodes.Brfalse_S,
  OpCodes.Brtrue_S,
  OpCodes.Beq_S,
  OpCodes.Bge_S,
  OpCodes.Bgt_S,
  OpCodes.Ble_S,
  OpCodes.Blt_S,
  OpCodes.Bne_Un_S,
  OpCodes.Bge_Un_S,
  OpCodes.Bgt_Un_S,
  OpCodes.Ble_Un_S,
  OpCodes.Blt_Un_S,
  OpCodes.Br,
  OpCodes.Brfalse,
  OpCodes.Brtrue,
  OpCodes.Beq,
  OpCodes.Bge,
  OpCodes.Bgt,
  OpCodes.Ble,
  OpCodes.Blt,
  OpCodes.Bne_Un,
  OpCodes.Bge_Un,
  OpCodes.Bgt_Un,
  OpCodes.Ble_Un,
  OpCodes.Blt_Un,
  OpCodes.Switch,
  OpCodes.Ldind_I1,
  OpCodes.Ldind_U1,
  OpCodes.Ldind_I2,
  OpCodes.Ldind_U2,
  OpCodes.Ldind_I4,
  OpCodes.Ldind_U4,
  OpCodes.Ldind_I8,
  OpCodes.Ldind_I,
  OpCodes.Ldind_R4,
  OpCodes.Ldind_R8,
  OpCodes.Ldind_Ref,
  OpCodes.Stind_Ref,
  OpCodes.Stind_I1,
  OpCodes.Stind_I2,
  OpCodes.Stind_I4,
  OpCodes.Stind_I8,
  OpCodes.Stind_R4,
  OpCodes.Stind_R8,
  OpCodes.Add,
  OpCodes.Sub,
  OpCodes.Mul,
  OpCodes.Div,
  OpCodes.Div_Un,
  OpCodes.Rem,
  OpCodes.Rem_Un,
  OpCodes.And,
  OpCodes.Or,
  OpCodes.Xor,
  OpCodes.Shl,
  OpCodes.Shr,
  OpCodes.Shr_Un,
  OpCodes.Neg,
  OpCodes.Not,
  OpCodes.Conv_I1,
  OpCodes.Conv_I2,
  OpCodes.Conv_I4,
  OpCodes.Conv_I8,
  OpCodes.Conv_R4,
  OpCodes.Conv_R8,
  OpCodes.Conv_U4,
  OpCodes.Conv_U8,
  OpCodes.Callvirt,
  OpCodes.Cpobj,
  OpCodes.Ldobj,
  OpCodes.Ldstr,
  OpCodes.Newobj,
  OpCodes.Castclass,
  OpCodes.Isinst,
  OpCodes.Conv_R_Un,
  null,
  null,
  OpCodes.Unbox,
  OpCodes.Throw,
  OpCodes.Ldfld,
  OpCodes.Ldflda,
  OpCodes.Stfld,
  OpCodes.Ldsfld,
  OpCodes.Ldsflda,
  OpCodes.Stsfld,
  OpCodes.Stobj,
  OpCodes.Conv_Ovf_I1_Un,
  OpCodes.Conv_Ovf_I2_Un,
  OpCodes.Conv_Ovf_I4_Un,
  OpCodes.Conv_Ovf_I8_Un,
  OpCodes.Conv_Ovf_U1_Un,
  OpCodes.Conv_Ovf_U2_Un,
  OpCodes.Conv_Ovf_U4_Un,
  OpCodes.Conv_Ovf_U8_Un,
  OpCodes.Conv_Ovf_I_Un,
  OpCodes.Conv_Ovf_U_Un,
  OpCodes.Box,
  OpCodes.Newarr,
  OpCodes.Ldlen,
  OpCodes.Ldelema,
  OpCodes.Ldelem_I1,
  OpCodes.Ldelem_U1,
  OpCodes.Ldelem_I2,
  OpCodes.Ldelem_U2,
  OpCodes.Ldelem_I4,
  OpCodes.Ldelem_U4,
  OpCodes.Ldelem_I8,
  OpCodes.Ldelem_I,
  OpCodes.Ldelem_R4,
  OpCodes.Ldelem_R8,
  OpCodes.Ldelem_Ref,
  OpCodes.Stelem_I,
  OpCodes.Stelem_I1,
  OpCodes.Stelem_I2,
  OpCodes.Stelem_I4,
  OpCodes.Stelem_I8,
  OpCodes.Stelem_R4,
  OpCodes.Stelem_R8,
  OpCodes.Stelem_Ref,
  OpCodes.Ldelem,
  OpCodes.Stelem,
  OpCodes.Unbox_Any,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  OpCodes.Conv_Ovf_I1,
  OpCodes.Conv_Ovf_U1,
  OpCodes.Conv_Ovf_I2,
  OpCodes.Conv_Ovf_U2,
  OpCodes.Conv_Ovf_I4,
  OpCodes.Conv_Ovf_U4,
  OpCodes.Conv_Ovf_I8,
  OpCodes.Conv_Ovf_U8,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  OpCodes.Refanyval,
  OpCodes.Ckfinite,
  null,
  null,
  OpCodes.Mkrefany,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  OpCodes.Ldtoken,
  OpCodes.Conv_U2,
  OpCodes.Conv_U1,
  OpCodes.Conv_I,
  OpCodes.Conv_Ovf_I,
  OpCodes.Conv_Ovf_U,
  OpCodes.Add_Ovf,
  OpCodes.Add_Ovf_Un,
  OpCodes.Mul_Ovf,
  OpCodes.Mul_Ovf_Un,
  OpCodes.Sub_Ovf,
  OpCodes.Sub_Ovf_Un,
  OpCodes.Endfinally,
  OpCodes.Leave,
  OpCodes.Leave_S,
  OpCodes.Stind_I,
  OpCodes.Conv_U,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  OpCodes.Prefix7,
  OpCodes.Prefix6,
  OpCodes.Prefix5,
  OpCodes.Prefix4,
  OpCodes.Prefix3,
  OpCodes.Prefix2,
  OpCodes.Prefix1,
  OpCodes.Prefixref
];
var LongOpCodes = [
  OpCodes.Arglist,
  OpCodes.Ceq,
  OpCodes.Cgt,
  OpCodes.Cgt_Un,
  OpCodes.Clt,
  OpCodes.Clt_Un,
  OpCodes.Ldftn,
  OpCodes.Ldvirtftn,
  null,
  OpCodes.Ldarg,
  OpCodes.Ldarga,
  OpCodes.Starg,
  OpCodes.Ldloc,
  OpCodes.Ldloca,
  OpCodes.Stloc,
  OpCodes.Localloc,
  null,
  OpCodes.Endfilter,
  OpCodes.Unaligned,
  OpCodes.Volatile,
  OpCodes.Tailcall,
  OpCodes.Initobj,
  OpCodes.Constrained,
  OpCodes.Cpblk,
  OpCodes.Initblk,
  null,
  OpCodes.Rethrow,
  null,
  OpCodes.Sizeof,
  OpCodes.Refanytype,
  OpCodes.Readonly
];
